/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_Class = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_Method = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_EQ = 7,
  anon_sym_COMMA = 8,
  anon_sym_DOLLAR = 9,
  anon_sym_DOT = 10,
  sym_comment = 11,
  sym_identifier = 12,
  sym_string = 13,
  sym_number = 14,
  sym_source_file = 15,
  sym__statement = 16,
  sym_class_definition = 17,
  sym_method_definition = 18,
  sym_assignment_statement = 19,
  sym__expression = 20,
  sym_parameters = 21,
  sym_system_call = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_parameters_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_Class] = "Class",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_Method] = "Method",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_DOT] = ".",
  [sym_comment] = "comment",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_class_definition] = "class_definition",
  [sym_method_definition] = "method_definition",
  [sym_assignment_statement] = "assignment_statement",
  [sym__expression] = "_expression",
  [sym_parameters] = "parameters",
  [sym_system_call] = "system_call",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_Class] = anon_sym_Class,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_Method] = anon_sym_Method,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_comment] = sym_comment,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_class_definition] = sym_class_definition,
  [sym_method_definition] = sym_method_definition,
  [sym_assignment_statement] = sym_assignment_statement,
  [sym__expression] = sym__expression,
  [sym_parameters] = sym_parameters,
  [sym_system_call] = sym_system_call,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_Class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Method] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_class_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_method_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_system_call] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 5,
  [13] = 7,
  [14] = 6,
  [15] = 8,
  [16] = 10,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 22,
  [26] = 23,
  [27] = 19,
  [28] = 24,
  [29] = 20,
  [30] = 30,
  [31] = 21,
  [32] = 30,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 34,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 39,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 46,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 41,
  [54] = 47,
  [55] = 55,
  [56] = 45,
  [57] = 49,
  [58] = 55,
  [59] = 50,
  [60] = 51,
  [61] = 42,
  [62] = 52,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '"', 2,
        '$', 13,
        '(', 9,
        ')', 10,
        ',', 12,
        '.', 14,
        '/', 3,
        '=', 11,
        'C', 20,
        'M', 18,
        '{', 6,
        '}', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '$') ADVANCE(13);
      if (lookahead == ')') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(15);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_Class);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_Method);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_Class] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_Method] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(44),
    [sym__statement] = STATE(3),
    [sym_class_definition] = STATE(3),
    [sym_method_definition] = STATE(3),
    [sym_assignment_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_Class] = ACTIONS(5),
    [anon_sym_Method] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      anon_sym_Class,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_Method,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(12), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [23] = 6,
    ACTIONS(5), 1,
      anon_sym_Class,
    ACTIONS(7), 1,
      anon_sym_Method,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_comment,
    STATE(5), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [46] = 6,
    ACTIONS(13), 1,
      anon_sym_Class,
    ACTIONS(17), 1,
      anon_sym_Method,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(12), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [69] = 6,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      anon_sym_Class,
    ACTIONS(34), 1,
      anon_sym_Method,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(40), 1,
      sym_identifier,
    STATE(5), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [92] = 6,
    ACTIONS(13), 1,
      anon_sym_Class,
    ACTIONS(17), 1,
      anon_sym_Method,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      sym_comment,
    STATE(7), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [115] = 6,
    ACTIONS(13), 1,
      anon_sym_Class,
    ACTIONS(17), 1,
      anon_sym_Method,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(12), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [138] = 6,
    ACTIONS(13), 1,
      anon_sym_Class,
    ACTIONS(17), 1,
      anon_sym_Method,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(49), 1,
      sym_comment,
    STATE(10), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [161] = 6,
    ACTIONS(13), 1,
      anon_sym_Class,
    ACTIONS(17), 1,
      anon_sym_Method,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 1,
      sym_comment,
    STATE(4), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [184] = 6,
    ACTIONS(13), 1,
      anon_sym_Class,
    ACTIONS(17), 1,
      anon_sym_Method,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(12), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [207] = 6,
    ACTIONS(13), 1,
      anon_sym_Class,
    ACTIONS(17), 1,
      anon_sym_Method,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    ACTIONS(59), 1,
      sym_comment,
    STATE(2), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [230] = 6,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(61), 1,
      anon_sym_Class,
    ACTIONS(64), 1,
      anon_sym_Method,
    ACTIONS(67), 1,
      sym_comment,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(12), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [253] = 6,
    ACTIONS(13), 1,
      anon_sym_Class,
    ACTIONS(17), 1,
      anon_sym_Method,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(12), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [276] = 6,
    ACTIONS(13), 1,
      anon_sym_Class,
    ACTIONS(17), 1,
      anon_sym_Method,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    ACTIONS(77), 1,
      sym_comment,
    STATE(13), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [299] = 6,
    ACTIONS(13), 1,
      anon_sym_Class,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_Method,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(79), 1,
      sym_comment,
    STATE(16), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [322] = 6,
    ACTIONS(13), 1,
      anon_sym_Class,
    ACTIONS(17), 1,
      anon_sym_Method,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    STATE(12), 5,
      sym__statement,
      sym_class_definition,
      sym_method_definition,
      sym_assignment_statement,
      aux_sym_source_file_repeat1,
  [345] = 3,
    ACTIONS(83), 1,
      anon_sym_DOLLAR,
    STATE(20), 2,
      sym__expression,
      sym_system_call,
    ACTIONS(85), 3,
      sym_identifier,
      sym_string,
      sym_number,
  [358] = 3,
    ACTIONS(87), 1,
      anon_sym_DOLLAR,
    STATE(29), 2,
      sym__expression,
      sym_system_call,
    ACTIONS(89), 3,
      sym_identifier,
      sym_string,
      sym_number,
  [371] = 2,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(93), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [381] = 2,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(97), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [391] = 2,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(101), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [401] = 2,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(105), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [411] = 2,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(109), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [421] = 2,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(113), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [431] = 2,
    ACTIONS(103), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(105), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [441] = 2,
    ACTIONS(107), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(109), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [451] = 2,
    ACTIONS(91), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(93), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [461] = 2,
    ACTIONS(111), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(113), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [471] = 2,
    ACTIONS(95), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(97), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [481] = 2,
    ACTIONS(117), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(115), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [491] = 2,
    ACTIONS(99), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(101), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [501] = 2,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(115), 3,
      anon_sym_Class,
      anon_sym_Method,
      sym_identifier,
  [511] = 3,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      aux_sym_parameters_repeat1,
  [521] = 3,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    ACTIONS(126), 1,
      sym_identifier,
    STATE(60), 1,
      sym_parameters,
  [531] = 3,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      aux_sym_parameters_repeat1,
  [541] = 3,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      sym_parameters,
  [551] = 3,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      aux_sym_parameters_repeat1,
  [561] = 1,
    ACTIONS(119), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [566] = 1,
    ACTIONS(136), 1,
      anon_sym_EQ,
  [570] = 1,
    ACTIONS(138), 1,
      anon_sym_EQ,
  [574] = 1,
    ACTIONS(140), 1,
      anon_sym_LBRACE,
  [578] = 1,
    ACTIONS(142), 1,
      anon_sym_LPAREN,
  [582] = 1,
    ACTIONS(144), 1,
      sym_identifier,
  [586] = 1,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
  [590] = 1,
    ACTIONS(148), 1,
      anon_sym_LBRACE,
  [594] = 1,
    ACTIONS(150), 1,
      sym_identifier,
  [598] = 1,
    ACTIONS(152), 1,
      anon_sym_LBRACE,
  [602] = 1,
    ACTIONS(154), 1,
      sym_identifier,
  [606] = 1,
    ACTIONS(156), 1,
      sym_identifier,
  [610] = 1,
    ACTIONS(158), 1,
      sym_identifier,
  [614] = 1,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
  [618] = 1,
    ACTIONS(162), 1,
      sym_identifier,
  [622] = 1,
    ACTIONS(164), 1,
      anon_sym_LBRACE,
  [626] = 1,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
  [630] = 1,
    ACTIONS(168), 1,
      anon_sym_DOT,
  [634] = 1,
    ACTIONS(170), 1,
      anon_sym_LBRACE,
  [638] = 1,
    ACTIONS(172), 1,
      sym_identifier,
  [642] = 1,
    ACTIONS(174), 1,
      anon_sym_DOT,
  [646] = 1,
    ACTIONS(176), 1,
      sym_identifier,
  [650] = 1,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
  [654] = 1,
    ACTIONS(180), 1,
      anon_sym_LPAREN,
  [658] = 1,
    ACTIONS(182), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 46,
  [SMALL_STATE(5)] = 69,
  [SMALL_STATE(6)] = 92,
  [SMALL_STATE(7)] = 115,
  [SMALL_STATE(8)] = 138,
  [SMALL_STATE(9)] = 161,
  [SMALL_STATE(10)] = 184,
  [SMALL_STATE(11)] = 207,
  [SMALL_STATE(12)] = 230,
  [SMALL_STATE(13)] = 253,
  [SMALL_STATE(14)] = 276,
  [SMALL_STATE(15)] = 299,
  [SMALL_STATE(16)] = 322,
  [SMALL_STATE(17)] = 345,
  [SMALL_STATE(18)] = 358,
  [SMALL_STATE(19)] = 371,
  [SMALL_STATE(20)] = 381,
  [SMALL_STATE(21)] = 391,
  [SMALL_STATE(22)] = 401,
  [SMALL_STATE(23)] = 411,
  [SMALL_STATE(24)] = 421,
  [SMALL_STATE(25)] = 431,
  [SMALL_STATE(26)] = 441,
  [SMALL_STATE(27)] = 451,
  [SMALL_STATE(28)] = 461,
  [SMALL_STATE(29)] = 471,
  [SMALL_STATE(30)] = 481,
  [SMALL_STATE(31)] = 491,
  [SMALL_STATE(32)] = 501,
  [SMALL_STATE(33)] = 511,
  [SMALL_STATE(34)] = 521,
  [SMALL_STATE(35)] = 531,
  [SMALL_STATE(36)] = 541,
  [SMALL_STATE(37)] = 551,
  [SMALL_STATE(38)] = 561,
  [SMALL_STATE(39)] = 566,
  [SMALL_STATE(40)] = 570,
  [SMALL_STATE(41)] = 574,
  [SMALL_STATE(42)] = 578,
  [SMALL_STATE(43)] = 582,
  [SMALL_STATE(44)] = 586,
  [SMALL_STATE(45)] = 590,
  [SMALL_STATE(46)] = 594,
  [SMALL_STATE(47)] = 598,
  [SMALL_STATE(48)] = 602,
  [SMALL_STATE(49)] = 606,
  [SMALL_STATE(50)] = 610,
  [SMALL_STATE(51)] = 614,
  [SMALL_STATE(52)] = 618,
  [SMALL_STATE(53)] = 622,
  [SMALL_STATE(54)] = 626,
  [SMALL_STATE(55)] = 630,
  [SMALL_STATE(56)] = 634,
  [SMALL_STATE(57)] = 638,
  [SMALL_STATE(58)] = 642,
  [SMALL_STATE(59)] = 646,
  [SMALL_STATE(60)] = 650,
  [SMALL_STATE(61)] = 654,
  [SMALL_STATE(62)] = 658,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 5, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_definition, 5, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_statement, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_statement, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_definition, 6, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_definition, 6, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 4, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_definition, 4, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_call, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_system_call, 4, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_definition, 7, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_definition, 7, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_definition, 8, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_definition, 8, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [146] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_objectscript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "objectscript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
